#Global configuration
spring:

  application:
    name: PadawanDWWM
    #H2 Configuration
    h2.console.enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/padawandwwm
    username: root
    password: macron
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

server:
  servlet:
    context-path: /padawan-dwwm

#Log level configuration
logging:
  level:
    error: DEBUG


